### ISSUE TITLE
Precedence in grammar

### ISSUE THREAD

**Issue by amir734jj** [joshwyant/ParserGenerator#1]
Thank you so much for sharing the code.

I am wondering if this parser supports precedence (e.g. `Multiply` with higher precedence than `Add`), if not how it can be implemented into the code. Thank you.

**Comment by joshwyant** [comment]
Yeah, you can do precedence by arranging your grammar expressions the exact same way you would in Backus-Naur form.

@amir734jj you also have a MIPS simulator like [mine](https://github.com/joshwyant/mips-machine)?
